#!/bin/sh /etc/rc.common

# OpenWrt init script for ruvname
# Usage: /etc/init.d/ruvname {start|stop|restart|enable|disable}

USE_PROCD=1

START=99
STOP=10

BIN=/usr/sbin/ruvname
CONF=/etc/ruvname/ruvname.toml
USER=root
GROUP=root

start_service() {
    procd_open_instance
    procd_set_param command $BIN -n -c $CONF
    procd_set_param user $USER
    procd_set_param group $GROUP
    procd_set_param respawn
    procd_set_param file $CONF
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    # Перечитать конфиг
    /etc/init.d/ruvname restart
}

stop_service() {
    # Обычно procd сам останавливает процесс
    :
}
