#!/bin/sh

# This is the "Service" file for RUVNAME in OPKG environment
# Usually lives in /opt/etc/init.d/ directory

ENABLED=yes
PROCS=ruvname
ARGS="-d -c /opt/etc/ruvname.conf -w /opt/var/lib/ruvname/ -l /opt/var/log/ruvname.log"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
