# Dockerfile.cross
FROM rustembedded/cross:x86_64-unknown-linux-musl-0.2.1

# Установите зависимости для GTK/webview
RUN apt update && apt install -y \
    pkg-config \
    libgtk-3-dev \
    libwebkit2gtk-4.0-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*