name: Build OpenWrt .ipk

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_ipk:
    name: Build .ipk for OpenWrt
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: 
          - mipsel-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-musl

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y musl-tools upx

      - name: Install Rust & Cross
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build ruvname
        run: cross build --target ${{ matrix.target }} --release

      - name: Setup OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/24.10.0/targets/generic/mipsel_24kc/openwrt-sdk-24.10.0-glibc-mipsel_24kc.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* openwrt-sdk

      - name: Copy package
        run: |
          mkdir -p openwrt-sdk/package/ruvname
          cp -r contrib/openwrt/package/ruvname/* openwrt-sdk/package/ruvname/
          cp target/${{ matrix.target }}/release/ruvname openwrt-sdk/package/ruvname/files/

      - name: Build .ipk
        working-directory: openwrt-sdk
        run: |
          make defconfig
          make package/ruvname/compile V=s

      - name: Extract .ipk
        run: |
          find openwrt-sdk/bin -name "*.ipk" -exec cp {} . \;
          mv *.ipk ruvname-${{ matrix.target }}-${{ github.event.release.tag_name }}.ipk

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ruvname-${{ matrix.target }}-${{ github.event.release.tag_name }}.ipk
          asset_name: ruvname-openwrt-${{ matrix.target }}-${{ github.event.release.tag_name }}.ipk
          tag: ${{ github.event.release.tag_name }}
          overwrite: true