name: Parallel Release & Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # v1.2.3
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  get_version:
    name: Get Version from Tag
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version detected: $VERSION"

  create_release:
    name: Create Parallel Release
    needs: get_version
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Parallel Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.get_version.outputs.version }}
          name: v${{ needs.get_version.outputs.version }}
          body: |
            ## New
            * Added new features.
            ## Bug Fixes & Improvements
            * Various fixes and stability improvements.
            ## Documentation & others
            * Updated documentation.
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux_gui:
    name: Build Linux GUI Binary
    needs: [create_release, get_version]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix APT sources and install deps
        run: |
          set -eux
          sudo rm -rf /etc/apt/sources.list.d/* /etc/apt/sources.list
          sudo tee /etc/apt/sources.list << 'EOF'
          deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
          deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
          EOF
          sudo apt update
          sudo apt install -y --no-install-recommends libwebkit2gtk-4.0-dev upx

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build release (GUI)
        run: cargo build --release

      - name: Optimize with UPX
        run: upx --best target/release/ruvname || echo "UPX not available, skipping..."

      - name: Package GUI
        run: |
          VERSION=${{ needs.get_version.outputs.version }}
          mkdir -p dist
          cp target/release/ruvname ruvname.toml README.md LICENSE adblock.txt dist/
          cd dist && zip -r ruvname-linux-amd64-v${VERSION}-gui.zip *

      - name: Upload GUI asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist/ruvname-linux-amd64-v${{ needs.get_version.outputs.version }}-gui.zip
          asset_name: ruvname-linux-amd64-v${{ needs.get_version.outputs.version }}-gui.zip
          asset_content_type: application/zip

  build_linux_nogui:
    name: Build Linux NoGUI Binary
    needs: [create_release, get_version]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build release (NoGUI)
        run: cargo build --release --no-default-features

      - name: Optimize with UPX
        run: upx --best target/release/ruvname || echo "UPX not available, skipping..."

      - name: Package NoGUI
        run: |
          VERSION=${{ needs.get_version.outputs.version }}
          mkdir -p dist
          cp target/release/ruvname ruvname.toml README.md LICENSE adblock.txt dist/
          cd dist && zip -r ruvname-linux-amd64-v${VERSION}-nogui.zip *

      - name: Upload NoGUI asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist/ruvname-linux-amd64-v${{ needs.get_version.outputs.version }}-nogui.zip
          asset_name: ruvname-linux-amd64-v${{ needs.get_version.outputs.version }}-nogui.zip
          asset_content_type: application/zip

  build_windows_nogui:
    name: Build Windows NoGUI Binary
    needs: [create_release, get_version]
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build release (NoGUI)
        run: cargo build --release --no-default-features

      - name: Optimize with UPX
        run: |
          upx.exe --best target/release/ruvname.exe || echo "UPX failed, using raw binary"

      - name: Package NoGUI
        run: |
          $version = "${{ needs.get_version.outputs.version }}"
          mkdir dist
          Copy-Item target/release/ruvname.exe, ruvname.toml, README.md, LICENSE, adblock.txt -Destination dist/
          Compress-Archive -Path dist/* -DestinationPath "dist/ruvname-windows-amd64-v$version-nogui.zip"

      - name: Upload Windows NoGUI
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist/ruvname-windows-amd64-v${{ needs.get_version.outputs.version }}-nogui.zip
          asset_name: ruvname-windows-amd64-v${{ needs.get_version.outputs.version }}-nogui.zip
          asset_content_type: application/zip

  build_deb:
    name: Build DEB Package
    needs: [create_release, get_version]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix APT sources and install deps
        run: |
          set -eux
          sudo rm -rf /etc/apt/sources.list.d/* /etc/apt/sources.list
          sudo tee /etc/apt/sources.list << 'EOF'
          deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
          deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
          EOF
          sudo apt update
          sudo apt install -y --no-install-recommends upx
          cargo install cross --locked

      - name: Build with musl
        run: cross build --target x86_64-unknown-linux-musl --release --no-default-features

      - name: Optimize with UPX
        run: upx --best target/x86_64-unknown-linux-musl/release/ruvname || echo "UPX not available"

      - name: Generate DEB
        run: PKGARCH=amd64 contrib/deb/generate.sh

      - name: Upload DEB
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ruvname-amd64-v${{ needs.get_version.outputs.version }}.deb
          asset_name: ruvname-linux-amd64-v${{ needs.get_version.outputs.version }}.deb
          asset_content_type: application/vnd.debian.binary-package
